python train_sample_reweight.py --loss-type ProxyNCA_pfix_confusion_sample500_196_192_reverse \
--helpful Influential_data/cub_ProxyNCA_pfix_harmful_confusion_testcls5.npy \
--harmful Influential_data/cub_ProxyNCA_pfix_helpful_confusion_testcls5.npy --model_dir models/dvi_data_cub_4_lossProxyNCA_pfix/ResNet_512_Model
python train_sample_reweight.py --loss-type ProxyNCA_pfix_confusion_sample500_130_112_reverse \
--helpful Influential_data/cub_ProxyNCA_pfix_harmful_confusion_testcls6.npy \
--harmful Influential_data/cub_ProxyNCA_pfix_helpful_confusion_testcls6.npy --model_dir models/dvi_data_cub_4_lossProxyNCA_pfix/ResNet_512_Model
python train_sample_reweight.py --loss-type ProxyNCA_pfix_confusion_sample500_124_128_reverse \
--helpful Influential_data/cub_ProxyNCA_pfix_harmful_confusion_testcls7.npy \
--harmful Influential_data/cub_ProxyNCA_pfix_helpful_confusion_testcls7.npy --model_dir models/dvi_data_cub_4_lossProxyNCA_pfix/ResNet_512_Model
python train_sample_reweight.py --loss-type ProxyNCA_pfix_confusion_sample500_111_110_reverse \
--helpful Influential_data/cub_ProxyNCA_pfix_harmful_confusion_testcls8.npy \
--harmful Influential_data/cub_ProxyNCA_pfix_helpful_confusion_testcls8.npy --model_dir models/dvi_data_cub_4_lossProxyNCA_pfix/ResNet_512_Model
python train_sample_reweight.py --loss-type ProxyNCA_pfix_confusion_sample500_144_142_reverse \
--helpful Influential_data/cub_ProxyNCA_pfix_harmful_confusion_testcls9.npy \
--harmful Influential_data/cub_ProxyNCA_pfix_helpful_confusion_testcls9.npy --model_dir models/dvi_data_cub_4_lossProxyNCA_pfix/ResNet_512_Model