python train_sample_reweight.py --loss-type ProxyNCA_pfix_confusion_theta12_130_112 \
--helpful Influential_data/cub_ProxyNCA_pfix_helpfulintersection_confusion_testcls6.npy \
--harmful Influential_data/cub_ProxyNCA_pfix_harmfulintersection_confusion_testcls6.npy --model_dir models/dvi_data_cub_4_lossProxyNCA_pfix/ResNet_512_Model
python train_sample_reweight.py --loss-type ProxyNCA_pfix_confusion_theta12_124_128 \
--helpful Influential_data/cub_ProxyNCA_pfix_helpfulintersection_confusion_testcls7.npy \
--harmful Influential_data/cub_ProxyNCA_pfix_harmfulintersection_confusion_testcls7.npy --model_dir models/dvi_data_cub_4_lossProxyNCA_pfix/ResNet_512_Model
python train_sample_reweight.py --loss-type ProxyNCA_pfix_confusion_theta12_111_110 \
--helpful Influential_data/cub_ProxyNCA_pfix_helpfulintersection_confusion_testcls8.npy \
--harmful Influential_data/cub_ProxyNCA_pfix_harmfulintersection_confusion_testcls8.npy --model_dir models/dvi_data_cub_4_lossProxyNCA_pfix/ResNet_512_Model
python train_sample_reweight.py --loss-type ProxyNCA_pfix_confusion_theta12_144_142 \
--helpful Influential_data/cub_ProxyNCA_pfix_helpfulintersection_confusion_testcls9.npy \
--harmful Influential_data/cub_ProxyNCA_pfix_harmfulintersection_confusion_testcls9.npy --model_dir models/dvi_data_cub_4_lossProxyNCA_pfix/ResNet_512_Model