# Copyright (C) 2019 NVIDIA Corporation.  All rights reserved.
# Licensed under the CC BY-NC-SA 4.0 license
# (https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode).

# logger options
image_save_iter: 2500         # How often do you want to save output images during training
image_display_iter: 100       # How often do you want to display output images during training
snapshot_save_iter: 5000      # How often do you want to save trained models
log_iter: 1                   # How often do you want to log the training stats

# optimization options
max_iter: 20000              # TODO 2889 / batch_size * 25 epochs
weight_decay: 0.0001          # weight decay
lr_gen: 0.004                # learning rate for the generator
lr_proxy: 400
init: kaiming                 # initialization [gaussian/kaiming/xavier/orthogonal]
gan_w: 1                      # weight of adversarial loss for image translation
fm_w: 1                       # weight on distance between gan features of style and translated image
r_w: 0.1                      # weight of image reconstruction loss

# model options
gen:
  n_res_blks: 4               # number of residual blocks in content encoder/decoder
  latent_dim: 512              # dimension of the latent code for the class model
  n_downs_class: 4            # number of downsampling layers in class model encoder

nb_classes: 100
sz_embed: 512
scale: 3

# data options
num_workers: 4
batch_size: 4
new_size: 224                 # first resize the shortest image side to this size
crop_image_height: 224        # random crop image of this height
crop_image_width: 224         # random crop image of this width
data_folder_train: /home/ruofan/PycharmProjects/SoftTriple/datasets/cub2011/train_sub
data_list_train: ./datasets/cub200_train.txt
data_folder_test: /home/ruofan/PycharmProjects/SoftTriple/datasets/cub2011/val
data_list_test: ./datasets/cub200_val.txt
